# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

mqtt:
  secret: MySecret
  image:
    name: mqtt
    version: 1
  storage:
    size: 10Gi
    class: "ibmc-file-silver"

base:
  image:
    name: ciml-base
    version: 1

postgres:
  image:
    name: ciml-db
    version: 1
  storage:
    size: 20Gi
    class: "ibmc-file-silver"

mqttWait:
  image:
    name: mqtt-wait
    version: 1 

predict:
  image:
    name: mqtt-predict
    version: 1

api:
  image:
    name: ciml-api
    version: 1

image:
  repository: registry.ng.bluemix.net/ciml
  tag: stable
  pullPolicy: Always
